# Pull the latest Keycloak image from quay.io
FROM quay.io/keycloak/keycloak:latest

# Copy the realm file to the Keycloak folder inside the container
COPY ./realm_config.json /opt/keycloak/data/import/

# Set up the environment variables for Keycloak
ENV  KEYCLOAK_ADMIN=admin
ENV  KEYCLOAK_ADMIN_PASSWORD=admin
ENV  DB_URL=jdbc:postgresql://postgres:5432/keycloak?ssl=allow 
ENV  DB=keycloak
ENV  DB_USERNAME=keycloak
ENV  DB_PASSWORD=keycloak

EXPOSE 8080

# Run Keycloak with the imported realm file (adjusted path to kc.sh)
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
