# This is a Docker Compose file for setting up services.

services:
  postgres:
    image: postgres:latest  # Define the PostgreSQL service
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    networks:
      - billing-bridge
    volumes:
      - ./keycloak/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    build:
      context: ./keycloak  # Build the Keycloak image from the Dockerfile in the current directory
    container_name: keycloak
    restart: always
    depends_on:
        - postgres  # Ensure that PostgreSQL is started before Keycloak
    volumes:
    - ./keycloak/keycloak-data:/opt/jboss/keycloak/standalone/data  # Persist Keycloak data
    networks:
    - billing-bridge
    ports:
    - "8080:8080"

  

networks:
  billing-bridge:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  keycloak-data:
    driver: local
